### PR TITLE
Use `git://` URI as `http://` results in errors

### PR DESCRIPTION
**Pull request by errordeveloper**

### CODE REVIEW

**Comment by jeremybennett** [comment]
Do you know why this happens? It works for me. I avoid git: because some corporate firewalls block it. Does it work if you use https rather than http?

(I recently changed the scripts for another architecture _from_ using `git://` to using `https://` to avoid these firewall problems)

**Comment by errordeveloper** [comment]
The weird error we see is:

> ```
> Cloning into 'binutils'...
> error: Unable to get pack index http://sourceware.org/git/binutils.git/objects/pack/pack-5c91465fe161ae3d12a444e8666ce64dff59d73f.idx
> error: Unable to get pack index http://sourceware.org/git/binutils.git/objects/pack/pack-7f8d063ca06e5552bcd01b99fa65b239e6824fc4.idx
> error: Unable to get pack index http://sourceware.org/git/binutils.git/objects/pack/pack-157ff349c96f2f7e7e05d49c0c88ad1d7be587a5.idx
> error: Unable to get pack index http://sourceware.org/git/binutils.git/objects/pack/pack-004da0a835d907f42f129e77f333c2af7f0ab140.idx
> error: Failed connect to sourceware.org:80; Connection timed out (curl_result = 7, http_code = 0, sha1 = 50dde019aed6e87005147a538acfcea9eb383eaa)
> error: Failed connect to sourceware.org:80; Connection timed out (curl_result = 7, http_code = 0, sha1 = 71d946cbccae7a4e5920c1560829974cbd677d15)
> error: Unable to find 5b8a04dda9202a47aa84ae93add8dedc3e19a145 under http://sourceware.org/git/binutils.git
> Cannot obtain needed tree 5b8a04dda9202a47aa84ae93add8dedc3e19a145
> while processing commit 1ff06815fbd1b281acd33dd31b1cf22c5737f4f9.
> ```

It cannot be that someone is force pushing just at the same time we clone it, right?

**Comment by simonpcook** [comment]
The issue of the binutils repository being broken seems to have been discussed already on the binutils mailing list (although not resolved): https://sourceware.org/ml/binutils/2013-09/msg00013.html

I doubt that it is the repository is changing whilst we are cloning it as I could browse to the pack index URLs git failed to fetch after my clone had failed.

**Comment by jeremybennett** [comment]
It looks like this is an error that is known about upstream, and so should be fixed fairly shortly. In addition, we know that binutils upstream is moving from CVS to git in the next few weeks anyway. So I suggest for now we hold on this patch.

If the upstream problem does not go away in the next few days, I'll look again.

What I will try to do is to add a tool chain option to allow the user to select which protocol to use. This is useful for developers with write access (who need git: access),  while other users generally get on better with http or https to avoid firewall problems.

Thanks for contributing. Please don't hesitate to make further suggestions.

**Comment by errordeveloper** [comment]
Fair enough, that's good news they will finally move to git!

**Pull request closed without merging**
